### ISSUE TITLE
[?BUG] Unable to access UrBackup behind a reverse proxy

### ISSUE THREAD

**Issue by alphamike-1612** [bartmichu/node-urbackup-server-api#4]
Hi, thank you for the widget.

I am trying to use this with UrBackup that is behind a reverse proxy. (Apache)

The setup is as described in the Server Administration Manual. ie.)
1. Link urbackup web-ui files to the document root in Apache.
2. Proxypass /x to fcgi://127.0.0.1:55413
3. Access Urbackup via SSL

I am relatively sure that my config is right, since if the proxypass directive is not set, the web-ui fails to load. (Only the static elements are served)

My widget in HomePage (that uses this api behind the scenes) passes the URL I give it directly to this wrapper.

```
 const server = new UrbackupServer({ 
   url: serviceWidget.url, 
   username: serviceWidget.username, 
   password: serviceWidget.password, 
 }); 
```

I had originally created an issue there, a contributor told me that the widget does nothing but pass it on to the wrapper. (Relevant discussion - https://github.com/gethomepage/homepage/discussions/2560)

I have tried the following without success.

1. https://pi-backup.internal
2. https://pi-backup.internal:443
3. https://pi-backup.internal:55413 (directly to the fcgi port)

The only thing that works is directly querying the UrBackup built in Web-Server that lives at port 55414 with HTTP. ie.) http://urbackup.internal:55414.

Does the wrapper support https? If so, is something wrong with my config? Could Self signed certificates be an issue?

Posting the entire Apache config if it'll be of more help.

```
<VirtualHost *:80>

	ServerName pi-backup.internal
	Redirect permanent / https://pi-backup.internal/
	#Redirect all port 80 requests to port 443.

</VirtualHost>

<VirtualHost *:443>

	ServerAdmin webmaster@localhost
	ServerName pi-backup.internal
	
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	SSLEngine on
	
	SSLProxyEngine on
	SSLProxyVerify none
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off

	SSLCertificateFile /etc/ssl/certs/pi-backup.crt
	SSLCertificateKeyFile /etc/ssl/private/pi-backup.key

	ProxyPreserveHost Off
	ProxyRequests Off
	
	ProxyPass /x fcgi://127.0.0.1:55413
	ProxyPassReverse /x fcgi://127.0.0.1:55413

</VirtualHost>
```

1. Adding/ Removing ProxyPassReverse has no effect.
2. Changing ProxyPreserveHost to on/off has no effect.
3. Changing ProxyRequests (Not really useful here) also has no effect.

Could you please help solve this issue?

Regards,
alphamike-1612

**Comment by bartmichu** [comment]
Hello @alphamike-1612 

I have literally zero experience with Apache server so it's difficult for me to debug this issue, but maybe we can figure it out together.

> Does the wrapper support https?

Yes, HTTPS is supported. In fact it's pretty much the only way I'm using it, also with a self-signed certificates.

> Could Self signed certificates be an issue?

Absolutely. By default Node will reject your certificate if it's not trusted. Did you try with `NODE_TLS_REJECT_UNAUTHORIZED` set to `0`?

For example:
```
...

// Don't use in production
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
process.removeAllListeners('warning');

const server = new UrbackupServer({ url: 'https://X.X.X.X:443', username: 'foo', password: 'bar' });

...
```

Try with IP address if possible.

**Comment by alphamike-1612** [comment]
Thank you @bartmichu .

Adding the 2 process lines in _index.js_ such that it looks like this
```
   constructor ({ url = 'http://127.0.0.1:55414', username = '', password = '' } = {}) {
    this.#url = new URL(url);
    this.#url.pathname = 'x';
    this.#username = username;
    this.#password = password;

    process.env.NODE_TLS_REJECT_UNAUTHORIZED ='0';
    process.removeAllListeners('warning');
  }
```
solved the issue. It works with both domain and IP without the need for the port number ie.) https://foobar.com. I have a double Reverse proxy in my setup. The first between fastCGI on port 55413 and /x on the domain https://pi-backup.internal. The second Reverse proxy from https://urbackup.internal to https://pi-backup.internal.

Using either domain (urbackup.internal or pi-backup.internal) or the IP, I am able to see data on the homepage webpage. 

I do not know Node (or any other programming language) so this might be ignorant, but can this value be set by the end user similar to how we give the URL, username and password in Homepage?

I would think that if this was possible, it would require you to set a variable that can be called with either true or false.

Also are there any security risks associated with this fix? Does this affect the entire Node JS server or is it applicable only when running the UrBackup server api wrapper?

Once again Thank you.!!!!

**Comment by bartmichu** [comment]
Good, I'm glad it works for you :)

> can this value be set by the end user similar to how we give the URL, username and password in Homepage? I would think that if this was possible, it would require you to set a variable that can be called with either true or false.

You are correct. I could implement this in the wrapper, but I really feel like it is out of scope for this project. Plus it is a bad security practice. It means a MITM attacker could swap certificates and you wouldn't notice. Treat it more as a workaround or a debugging tool. A proper solution would be to:

1) use a signed certificate, for example Let's Encrypt
2) install your root certificate

Also, if you are looking for different ways of monitoring UrBackup Server, you may be interested in my other project - a command line tool called urbstat. [Here is a demo](https://asciinema.org/a/557533) of how it looks like.

**Comment by alphamike-1612** [comment]
@bartmichu 

I have installed the certificate to my root in Debian such that curl and other services no longer complain about invalid certificates, but it appears that node has it's own default set of root certificates and doesn't use the ones inside /etc/ssl/certs.

I tried setting it as a variable in index.js of the wrapper like you asked me to above, but like
```
proccess.env.NODE_EXTRA_CA_CERTS = '/full/path/to/ca/file.crt';
```
I also added the `process.removeAllListeners('warning');` but there is no change with or without it. I am confused as to how to add the certificate to Node and googling hasn't helped me.

Could you please guide me on the process for the same? Am I required to run `npm build` and `npm install` again for the certs to be added? Or can it be done otherwise? I understand that we have crossed the scope of this bug and your wrapper, but would be much obliged if you could help me with this.

P.S - Adding Let's Encrypt is not a possibility for me as I am behind a CGNAT Internet connection and cannot forward ports. I also do not own any custom domains.

Thank you.

**Comment by alphamike-1612** [comment]
I have still not found the way to address this issue via the index.js file. But adding an environment variable to the systemd service file that runs this service, makes it work as expected.

In this case, it is no longer required to add NODE_TLS_REJECT_UNAUTHORIZED to the index.js file. This prevents MITM attacks.

In your systemd service file, under the [Service] section, add this line Environment = "NODE_EXTRA_CA_CERTS=<path-to-ca-file.crt>"

Do not know how accurate this is, but I remember reading somewhere that the certificates need to be in PEM format. ie.) if you run cat <ca-file> your output should begin with ----BEGIN CERTIFICATE---- and end with ---END CERTIFICATE---

I am closing this issue as it is out of bounds of the developer as he has stated above.

Thank you for all the help @bartmichu

**Comment by bartmichu** [comment]
@alphamike-1612 thanks for sharing! Am I right thinking that with your method you no longer need to disable `NODE_TLS_REJECT_UNAUTHORIZED`? If so, looks like a perfect solution to me.

**Comment by alphamike-1612** [comment]
Yes that is correct. Have updated the reply with this information.

**Comment by bartmichu** [comment]
Perfect. I will update the README file as well to include your solution.
